<a href="https://colab.research.google.com/github/ssyyjj1012/data-analysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy 
- Numerical Python 의 줄인말
- 고성능의 과학계산 컴퓨팅과 데이터 분석에 필요한 기본 패키지
- Numpy 배열과 배열 기반의 컴퓨팅에 대한 이해는 pandas의 활용 능력을 향상 


### Numpy의 특징
- 빠르고 메모리를 효율적으로 사용
- 다차원 배열인 ndarray(벡터 산수연산과 브로드캐스팅 가능)
- 반복문을 작성 불필요
- 전체 데이터 배열에 대한 빠른 연산을 제공하는 표준 수학 함수
- 배열 데이터를 디스크에 쓰기/읽기
- 선형대수, 난수발생기, 푸리에 변환 가능
- C, C++ 포트란으로 쓰여진 코드 통합(글루 언어)

### ndarray : Numpy 배열의 특징
- 배열의 항목을 동일한 타입이어야 한다.
- 파이썬 리스트와는 달리 벡토화된 연산과 완전한 배열처리를 실행
- 배열을 특별히 빠르게 하기 위해 최적화된 C API 를 사용
- 파이썬처럼 NumPy 배열의 0으로 시작하는 인덱스가 생성
- 데이터 타입은 특별한 오브젝트로 표현

# 01 NumPy 배열 생성 - 1차 배열 만들기

In [2]:
import numpy as np
a = np.arange(5) # 자동으로 배열 생성
a

array([0, 1, 2, 3, 4])

In [3]:
a.shape

(5,)

In [4]:
b = np.array([0,1,2,3,4]) # 수동으로 배열 생성
b 

array([0, 1, 2, 3, 4])

## 01 NumPy 배열 생성 - 2차 배열 만들기



In [5]:
m = np.array([np.arange(2),np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [6]:
m.shape

(2, 2)

## **배열 인덱싱**

In [7]:
m[0,0] = 0
m[0,1] = 1
m[1,0] = 2
m[1,1] = 3
m

array([[0, 1],
       [2, 3]])

## **배열 인덱싱 2**

파이썬에서 사용하는 일반적인 자르기/인덱싱 방법으로 가능

(2차원 이상은 쉼표(,)를 기준으로 차원별로 인덱싱 적용)

In [10]:
a[1:3]

array([1, 2])

In [11]:
m[0,1:]

array([1])

## **배열 연산하기**

In [8]:
m + 2

array([[2, 3],
       [4, 5]])

In [9]:
m * 2

array([[0, 2],
       [4, 6]])

## 01 NumPy 초기화 배열 생성

numpy.zeros()

: 주어진 모양과 타입대로 0으로 채워진 새로운 배열 생성


In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5, dtype= np.int)

array([0, 0, 0, 0, 0])

In [14]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [15]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [16]:
np.zeros((2,),dtype=[('x', 'i4'),('y','i4')])

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

## 01 NumPy 랜덤 배열 생성

np.random.randn(d0,d1 ... dn)

: 정규화 분산 데이터로부터 랜덤한 값 리턴

In [17]:
np.random.randn()

-0.32281912413457503

In [18]:
2.5 * np.random.randn(2,4)*3

array([[ 13.91361603,   3.12767818, -11.68961013,  -4.72856919],
       [ -2.77031825,  -4.02118439,   3.10506701, -12.51084888]])

### np.random.randint(n1, n2)

: n1 ~ n2 사이의 정수 생성

In [19]:
np.random.randint(2, size = 10)

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0])

In [20]:
np.random.randint(1, size = 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 연습문제

In [28]:
a = np.array([np.arange(3),np.arange(3)])
a

array([[0, 1, 2],
       [0, 1, 2]])

In [34]:
a = np.array([np.arange(3),np.arange(3)+3,np.arange(3)+6])*3
a

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])